apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.lb.port }}
      targetPort: {{ .Values.lb.targetPort }}
      protocol: {{ .Values.lb.protocol }}
      name: {{ .Values.lb.name }}
  selector: {{ .Values.appName }}