apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "node-tenpo-api-config-zefc"
  namespace: "default"
  labels:
    app: {{ .Values.appName }}
data:
  TENPO_SECRET: {{ .Values.tenposecret }}
  TENPO_PASSW_LEN: {{ .Values.tenpopaswlen }}
  TENPO_DB_IP: {{ .Values.db.ip }}
  TENPO_DB_USER: {{ .Values.db.user }}
  TENPO_DB_PASSW: {{ .Values.db.passw }}
  TENPO_DB: {{ .Values.db.dbname }}
  TENPO_ENV: {{ .Values.environment }}