apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appName }}
        env:
        - name: "TENPO_SECRET"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_SECRET"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_PASSW_LEN"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_PASSW_LEN"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_DB_IP"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_DB_IP"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_DB_USER"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_DB_USER"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_DB_PASSW"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_DB_PASSW"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_DB"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_DB"
              name: {{ .Values.appName }}-config-zefc
        - name: "TENPO_ENV"
          valueFrom:
            configMapKeyRef:
              key: "TENPO_ENV"
              name: {{ .Values.appName }}-config-zefc