apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.lb.port }}
      targetPort: {{ .Values.lb.targetPort }}
      protocol: {{ .Values.lb.protocol }}
      name: {{ .Values.lb.name }}
  selector: 
    app: {{ .Values.appName }}